### ISSUE TITLE
Animation Only Works On Initial Event, Breaks On Subsequent Events

### ISSUE THREAD

**Issue by johnnyshankman** [ngokevin/kframe#58] opened 2017-04-13 19:50 UTC
Here's my component
```
<a-entity class="player-button" id="back-button"
  geometry="primitive: plane; height: 1; width: 1"
  position="0 0 0"
  material="shader: flat; src: #back; transparent: true;"
  animation__enter="property: scale; easing: linear; dir: forward; dur: 100; to: 1.2 1.2 1.2; startEvents: mouseenter;"
  animation__leave="property: scale; easing: linear; dir: forward; dur: 100; to: 1 1 1; startEvents: mouseleave;">
</a-entity>
```

`animation__enter` happens once and then never happens on subsequent `mouseenter` events. What's weird is that it does actually change the scale it just ceases to animate the change (pops into place).

Further more, after executing `animation__enter`, `animation__leave` never works. Once again, the values change on the event, but there's no animation.

It's very hard to see in this video http://recordit.co/qa9op6AeIc but what happens is that the initial enter animation works but then on mouseleave it breaks. Then I hover over the pause button and the same thing happens, enter works but all else fails from then on in -- meaning each component gets one chance to animate. Very weird.

**Comment by johnnyshankman** [comment] 2017-04-13 19:52
In the meantime I have to revert back to using `<a-animation>` because this is a gamebreaker until I know what I've done wrong! Would much prefer the concise syntax of this component though.

**Comment by limzykenneth** [comment] 2017-05-05 08:41
I have the same issue as well
```html
<a-plane class="panel" position="0 2 -5" width="2" height="2" color="#ff0"
         material="side:double"
         sound="src: #armstrong; on: click;"
         animation__1="property: scale; dur: 500; from: 1 1 1; to: 1.2 1.2 1.2; startEvents: mouseenter; pauseEvents: mouseleave;"
         animation__2="property: scale; dur: 500; from: 1.2 1.2 1.2; to: 1 1 1; startEvents: mouseleave; pauseEvents: mouseenter"></a-plane>
```

That makes this component unusable for what I need to do. Hopefully it gets fixed soon because I really like the process of attaching an attribute instead of `<a-animation>`'s creating an element then attaching attributes to that.

**Comment by ngokevin** [comment] 2017-05-05 11:43
Currently working on it while throwing unit tests at it.

**Comment by ip** [comment] 2017-05-08 00:40
I also experience this issue, it would be great if somebody fix it.

**Comment by wazynski** [comment] 2017-05-23 13:00
I am having a similar issuse with these animations:

```
animation__fadeout={{
     property: 'material.color',
     dur: '1000',
     from: '#FFF',
     to: '#000',
     startEvents: 'set-image-fade-out',
}}

animation__fadein={{
     property: 'material.color',
     dur: '1000',
     from: '#000',
     to: '#FFF',
     startEvents: 'set-image-fade-in',
}}
```

The first time either of the startEvents are called the animation works perfectly. On subsequent calls the material colour changes but there is no tranisitions, like the duration has been set to 0.

**Comment by morandd** [comment] 2017-06-16 16:02
a bit related, I am using d3 to do animations however d3's default interpolators get confused by the switch between string attributes and Vec3 objects. E.g the `scale` attr is sometimes a string like "3 1 3" and other times a Vec3 object like {x: 3, y:1, z:3}.  Anyway, just noticed this and thought I'd mention it here, if for no other reason than as a warning flag for others

**Comment by madebynoam** [comment] 2017-06-23 15:51
@ngokevin I did some investigating and some experiments with refactoring the component on my side. I found that you can build the anime config at beginAnimation time, and this would allow you to re run animations with better behavior (because the 'from' value becomes updated with the current value of the entity). In the current component build, anime config is only built once at component update time, which appears to be the cause of some of the bugs (it always has a static from value).

Also I noticed that Anime itself has a delay attribute, so thought to just pass it through rather than try to do it through the A-Frame component.

You can take a look at my refactoring on glitch: 
https://glitch.com/edit/#!/rel-animation-component?path=public/animation.js:225:66

Running demo: 
https://rel-animation-component.glitch.me/
Click the image and it will scale up and the gray button will appear.
Click the gray button and the image will animate back to scale .5 with no 'glitches'.

I'm excited to see what you think. I'd be happy to help out if you think it's worth a pull request.

**Comment by c4augustus** [comment] 2017-07-22 14:28
Yes, I needed this fix as well, so I forked the original repo and merged the fix into my master. Thanks for it.

**Closed** 2018-06-27 06:22 UTC
Labels: components/animation
